<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>อายุคำนวนอัตโนมัติ</description>
   <name>auto_age</name>
   <tag></tag>
   <elementGuidId>a3c2139e-0f06-4394-b73f-446eed909f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;age&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
