<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ใส่วันเกิด</description>
   <name>birthday_in</name>
   <tag></tag>
   <elementGuidId>6e3cdb7e-a4df-4859-91c6-5a65e5279ec3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/section/div/div/div/div/form/div[4]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
